### ISSUE TITLE
[Bug] Integration test failures

### ISSUE THREAD

**Issue by adityeah8969** [rapyuta-robotics/rapyuta-io-sdk#19]
The recent devel integration test fails with the following logs.

`======================================================================

## ERROR: package.routed_networks_tests.RoutedNetworkTest.test_add_device_routed_network
Traceback (most recent call last):
  File "/home/aditya/workspace/rapyuta-io-sdk/sdk_test/package/routed_networks_tests.py", line 97, in test_add_device_routed_network
    prov_config.add_device('default', self.supervisor_device, ignore_device_config=ignore_device_config)
  File "/home/aditya/workspace/rapyuta-io-sdk/rapyuta_io/clients/package.py", line 559, in add_device
    raise InvalidParameterException('ros_workspace is not set')

# rapyuta_io.utils.error.InvalidParameterException: ros_workspace is not set
## ERROR: coreapi.query_metrics_test.MetricsTests.test_list_metrics
Traceback (most recent call last):
  File "/home/aditya/workspace/rapyuta-io-sdk/sdk_test/coreapi/query_metrics_test.py", line 70, in test_list_metrics
    list_metrics_query = ListMetricsRequest(Entity.PROJECT, self.config._project.guid,

# AttributeError: 'NoneType' object has no attribute 'guid'
## ERROR: coreapi.query_metrics_test.MetricsTests.test_list_tag_keys
Traceback (most recent call last):
  File "/home/aditya/workspace/rapyuta-io-sdk/sdk_test/coreapi/query_metrics_test.py", line 79, in test_list_tag_keys
    list_tag_keys_query = ListTagKeysRequest(Entity.PROJECT, self.config._project.guid,

# AttributeError: 'NoneType' object has no attribute 'guid'
## ERROR: coreapi.query_metrics_test.MetricsTests.test_list_tag_values
Traceback (most recent call last):
  File "/home/aditya/workspace/rapyuta-io-sdk/sdk_test/coreapi/query_metrics_test.py", line 89, in test_list_tag_values
    list_tag_values_query = ListTagValuesRequest(Entity.PROJECT, self.config._project.guid, tag,

# AttributeError: 'NoneType' object has no attribute 'guid'
## ERROR: package.cloud_transform_test.TestCloudTransform.test_deploy_cloud_transform
Traceback (most recent call last):
  File "/home/aditya/workspace/rapyuta-io-sdk/sdk_test/package/cloud_transform_test.py", line 86, in test_deploy_cloud_transform
    self.deploy_talker_package()
  File "/home/aditya/workspace/rapyuta-io-sdk/sdk_test/package/cloud_transform_test.py", line 61, in deploy_talker_package
    provision_config.add_device('default', self.device, ignore_device_config=['network_interface'])
  File "/home/aditya/workspace/rapyuta-io-sdk/rapyuta_io/clients/package.py", line 559, in add_device
    raise InvalidParameterException('ros_workspace is not set')

# rapyuta_io.utils.error.InvalidParameterException: ros_workspace is not set
## ERROR: package.cloud_scoped_targeted_test.TestScopedTargeted.test_scoped_targeted_package
Traceback (most recent call last):
  File "/home/aditya/workspace/rapyuta-io-sdk/sdk_test/package/cloud_scoped_targeted_test.py", line 69, in test_scoped_targeted_package
    provision_config.add_device(self.ST_DEV_COMP, self.device, ignore_device_config=['network_interface'])
  File "/home/aditya/workspace/rapyuta-io-sdk/rapyuta_io/clients/package.py", line 559, in add_device
    raise InvalidParameterException('ros_workspace is not set')

# rapyuta_io.utils.error.InvalidParameterException: ros_workspace is not set
## ERROR: package.cloud_scoped_targeted_test.TestScopedTargeted.test_scoped_targeted_package_non_alias_depends
Traceback (most recent call last):
  File "/home/aditya/workspace/rapyuta-io-sdk/sdk_test/package/cloud_scoped_targeted_test.py", line 91, in test_scoped_targeted_package_non_alias_depends
    provision_config.add_device(self.ST_DEV_COMP, self.device, ignore_device_config=['network_interface'])
  File "/home/aditya/workspace/rapyuta-io-sdk/rapyuta_io/clients/package.py", line 559, in add_device
    raise InvalidParameterException('ros_workspace is not set')

# rapyuta_io.utils.error.InvalidParameterException: ros_workspace is not set
## ERROR: package.volume_test.TestVolume.test_03_device_volume_with_executable_mounts
Traceback (most recent call last):
  File "/home/aditya/workspace/rapyuta-io-sdk/sdk_test/package/volume_test.py", line 80, in test_03_device_volume_with_executable_mounts
    self.deployment.poll_deployment_till_ready()
  File "/home/aditya/workspace/rapyuta-io-sdk/rapyuta_io/clients/deployment.py", line 290, in poll_deployment_till_ready
    return _poll_till_ready(self, retry_count, sleep_interval)
  File "/home/aditya/workspace/rapyuta-io-sdk/rapyuta_io/clients/deployment.py", line 46, in _poll_till_ready
    raise DeploymentNotRunningException(msg, deployment_status=dep_status)
rapyuta_io.utils.error.DeploymentNotRunningException: Deployment might not progress: phase=Failed to start status=Deployment not running errors=['DEP_317']`

┆Issue is synchronized with this [Wrike task](https://www.wrike.com/open.htm?id=904731054)

**Comment by pallabpain** [comment]
Pretty old issue. No longer applicable.
